export const SET_HOME_TRUE = "SET_HOME_TRUE";
export const SET_HOME_FALSE = "SET_HOME_FALSE";
export const SET_MENU_ACTIVE = "SET_MENU_ACTIVE";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const GET_CATEGORIES_AND_FILTER_BY_FIRST_CATEGORY =
  "GET_CATEGORIES_AND_FILTER_BY_FIRST_CATEGORY";
// export const RESET_RECIPES_REDUCER = "RESET_RECIPES_REDUCER";
export const GET_RANDOM_CATEGORIES = "GET_RANDOM_CATEGORIES";
export const GET_SEARCH = "GET_SEARCH";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const GET_DETAILS = "GET_DETAILS";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
