//export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_HOME_TRUE = "SET_HOME_TRUE";
export const SET_HOME_FALSE = "SET_HOME_FALSE";
export const SET_MENU_ACTIVE = "SET_MENU_ACTIVE";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const GET_CATEGORIES_AND_FILTER_BY_FIRST_CATEGORY =
  "GET_CATEGORIES_AND_FILTER_BY_FIRST_CATEGORY";
